### ISSUE TITLE
installation failed on app builder 6.2

### ISSUE THREAD

**Issue by rbj2000** [entando-samples/standard-demo-bundle#1]
I have entando 6.2 running on kubernets. I was able to create demo resource by command: sudo entando-bundle from-git  --name standard-demo --namespace entando --repository https://github.com/entando/standard-demo-bundle.git

entando-bundle version 6.1.0

When I tried to install it from Admin I got error (log from de-container):

2020-09-07 07:19:44.636  INFO 1 --- [           main] l.lockservice.StandardLockService        : Successfully released change log lock
2020-09-07 07:20:14.819  INFO 1 --- [nio-8083-exec-2] o.a.c.c.C.[.[.[/digital-exchange]        : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-09-07 08:30:22.363  INFO 1 --- [nio-8083-exec-2] o.e.k.s.d.j.EntandoBundleInstallService  : Verify validity of a new install job for component standard-demo
2020-09-07 08:30:22.364  INFO 1 --- [nio-8083-exec-2] o.e.k.s.d.j.EntandoBundleInstallService  : Extracting version latest from bundle
2020-09-07 08:30:22.435  INFO 1 --- [       Thread-3] o.e.k.s.d.j.EntandoBundleInstallService  : Started new install job for component standard-demo@v0.0.1
2020-09-07 08:30:22.498  INFO 1 --- [       Thread-3] o.e.k.m.b.downloader.BundleDownloader    : Downloading bundle standard-demo@v0.0.1 locally
2020-09-07 08:30:23.956  INFO 1 --- [       Thread-3] o.e.k.m.b.downloader.BundleDownloader    : Bundle downloaded locally at path /tmp/6927125764765706333
2020-09-07 08:30:24.001 ERROR 1 --- [       Thread-3] o.e.k.s.d.j.EntandoBundleInstallService  : An error occurred while reading components from the bundle

org.entando.kubernetes.exception.EntandoComponentManagerException: Error reading bundle
        at org.entando.kubernetes.model.bundle.processor.FragmentProcessor.process(FragmentProcessor.java:53) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.lambda$getInstallableComponentsByPriority$6(EntandoBundleInstallService.java:215) ~[classes!/:6.0.57]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_242]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_242]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_242]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.getInstallableComponentsByPriority(EntandoBundleInstallService.java:218) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.getBundleInstallableComponents(EntandoBundleInstallService.java:202) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.lambda$submitInstallAsync$5(EntandoBundleInstallService.java:148) ~[classes!/:6.0.57]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "locked" (class org.entando.kubernetes.model.bundle.descriptor.FragmentDescriptor), not marked as ignorable (3 known properties: "guiCode", "code", "guiCodePath"])
 at [Source: (FileInputStream); line: 2, column: 14] (through reference chain: org.entando.kubernetes.model.bundle.descriptor.FragmentDescriptor["locked"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at org.entando.kubernetes.model.bundle.BundleReader.readDescriptorFile(BundleReader.java:100) ~[classes!/:6.0.57]
        at org.entando.kubernetes.model.bundle.BundleReader.readDescriptorFile(BundleReader.java:74) ~[classes!/:6.0.57]
        at org.entando.kubernetes.model.bundle.processor.FragmentProcessor.process(FragmentProcessor.java:43) ~[classes!/:6.0.57]
        ... 13 common frames omitted

2020-09-07 08:30:33.302  INFO 1 --- [nio-8083-exec-8] o.e.k.s.d.j.EntandoBundleInstallService  : Verify validity of a new install job for component standard-demo
2020-09-07 08:30:33.304  INFO 1 --- [nio-8083-exec-8] o.e.k.s.d.j.EntandoBundleInstallService  : Extracting version latest from bundle
2020-09-07 08:30:33.308  INFO 1 --- [       Thread-4] o.e.k.s.d.j.EntandoBundleInstallService  : Started new install job for component standard-demo@v0.0.1
2020-09-07 08:30:33.316  INFO 1 --- [       Thread-4] o.e.k.m.b.downloader.BundleDownloader    : Downloading bundle standard-demo@v0.0.1 locally
2020-09-07 08:30:34.734  INFO 1 --- [       Thread-4] o.e.k.m.b.downloader.BundleDownloader    : Bundle downloaded locally at path /tmp/8752619201186883677
2020-09-07 08:30:34.751 ERROR 1 --- [       Thread-4] o.e.k.s.d.j.EntandoBundleInstallService  : An error occurred while reading components from the bundle

org.entando.kubernetes.exception.EntandoComponentManagerException: Error reading bundle
        at org.entando.kubernetes.model.bundle.processor.FragmentProcessor.process(FragmentProcessor.java:53) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.lambda$getInstallableComponentsByPriority$6(EntandoBundleInstallService.java:215) ~[classes!/:6.0.57]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_242]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_242]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_242]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.getInstallableComponentsByPriority(EntandoBundleInstallService.java:218) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.getBundleInstallableComponents(EntandoBundleInstallService.java:202) ~[classes!/:6.0.57]
        at org.entando.kubernetes.service.digitalexchange.job.EntandoBundleInstallService.lambda$submitInstallAsync$5(EntandoBundleInstallService.java:148) ~[classes!/:6.0.57]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "locked" (class org.entando.kubernetes.model.bundle.descriptor.FragmentDescriptor), not marked as ignorable (3 known properties: "guiCode", "code", "guiCodePath"])
 at [Source: (FileInputStream); line: 2, column: 14] (through reference chain: org.entando.kubernetes.model.bundle.descriptor.FragmentDescriptor["locked"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at org.entando.kubernetes.model.bundle.BundleReader.readDescriptorFile(BundleReader.java:100) ~[classes!/:6.0.57]
        at org.entando.kubernetes.model.bundle.BundleReader.readDescriptorFile(BundleReader.java:74) ~[classes!/:6.0.57]
        at org.entando.kubernetes.model.bundle.processor.FragmentProcessor.process(FragmentProcessor.java:43) ~[classes!/:6.0.57]
        ... 13 common frames omitted

**Comment by joewhite101** [comment]
@w-caffiero-entando @Kerruba any ideas? Looks like a field mismatch in the fragment?

**Comment by Kerruba** [comment]
Seems to me that the `locked` field is the problem as is not supported by the fragment descriptor. Could you post the fragment descriptor?

**Comment by Kerruba** [comment]
Actually I think I've found it, the problem seems to be with the fragment extractor. @ffleandro could you have a look?

**Comment by rbj2000** [comment]
> Seems to me that the `locked` field is the problem as is not supported by the fragment descriptor. Could you post the fragment descriptor?

Here is one:  angular-descriptor.yaml
code: angular
locked: false
widgetType:
  code: null
  title: null
pluginCode: null

**Comment by ffleandro** [comment]
This Bundle is still a Work in Progress, as we still need to finish several stories over the next couple of sprints to fully support installing it from the `entando-component-manager`.

**Comment by ffleandro** [comment]
This has already been fixed by latest commits, however this is not yet installable as we still need to complete a couple of stories in order to fully support this Bundle.
